Update to Swift 3
hyperoslo/Compass pull request #40
Opened 2016-10-03 20:45 UTC by onmyway133

2016-10-04 07:30 UTC, onmyway133 commented on Tests/Compass/Helpers.swift
> -extension MutableCollectionType where Index == Int {
Have a hard time extending `MutableCollection`, so extend on `Array` for now

2016-10-04 07:39 UTC, vadymmarkov requested changes

2016-10-04 07:39 UTC, vadymmarkov commented on Sources/Router.swift
> +  func handle(_ routeError: Error, from currentController: Controller)
I would leave `routeError` in function signature, or maybe just `error`.

2016-10-04 07:39 UTC, vadymmarkov commented on Sources/Compass.swift
> +  static func parseAsURL(_ url: URL, payload: Any? = nil) -> Location? {
Maybe `parseAsUrl`?

2016-10-04 07:39 UTC, vadymmarkov commented on Sources/Compass.swift
> +  public static func navigate(_ urn: String, scheme: String = Compass.scheme) {
Maybe `navigate(to urn`

2016-10-04 07:39 UTC, vadymmarkov commented on Sources/String+Extensions.swift
> +  func replace(_ string: String, with withString: String) -> String {
Why do we need this method?

2016-10-04 07:39 UTC, vadymmarkov commented on Sources/TypeAlias.swift
> +  func openURL(_ url: URL) {
I think `func open(url: URL)` is better.

2016-10-04 07:39 UTC, vadymmarkov commented on Sources/TypeAlias.swift
> +  func openURL(_ url: Foundation.URL) {
Don't need Foundation here.

2016-10-04 19:35 UTC, onmyway133 commented on Sources/String+Extensions.swift
> +  func replace(_ string: String, with withString: String) -> String {
It's just a syntactic sugar

2016-10-04 19:35 UTC, onmyway133 commented on Sources/TypeAlias.swift
> +  func openURL(_ url: URL) {
👍

2016-10-04 19:45 UTC, onmyway133 commented
Fixed as you suggest @vadymmarkov 😉

2016-10-04 21:35 UTC, vadymmarkov commented on Sources/String+Extensions.swift
> +  func replace(_ string: String, with withString: String) -> String {
Yeah, but it makes less sense in Swift 3 I think.

2016-10-05 05:23 UTC, zenangst commented on Sources/String+Extensions.swift
> +  func replace(_ string: String, with withString: String) -> String {
I agree, lets get rid of the Sugar that are fixed by Apple in Swift 3.

2016-10-05 05:23 UTC, zenangst commented on Sources/TypeAlias.swift
> +  func openURL(_ url: URL) {
❤️

2016-10-05 08:55 UTC, RamonGilabert commented on Sources/TypeAlias.swift
> +  func openURL(_ url: URL) {
Putting the _ seems to be the default everywhere tho. Which is a bit stupid, since, if everyone needs underscore, why don't we delete the underscore.

2016-10-05 09:00 UTC, vadymmarkov commented on Sources/TypeAlias.swift
> +  func openURL(_ url: URL) {
@RamonGilabert I think the idea is to move the last part of the function's name to be an argument name, like in the example above (like in good old Objective C times) So we have to use `_` as less as possible.

2016-10-05 09:02 UTC, vadymmarkov commented on Sources/String+Extensions.swift
> +  func replace(_ string: String, with withString: String) -> String {
@onmyway133 Would you mind to remove this functions an use `replacingOccurrences(of: string, with: withString)` instead?

2016-10-05 09:03 UTC, RamonGilabert commented on Sources/TypeAlias.swift
> +  func openURL(_ url: URL) {
Yeah, sorry, I thought you suggested `func openURL(url: URL)`.

2016-10-05 09:03 UTC, vadymmarkov commented on Sources/Compass.swift
> +  public static func parse(_ url: URL, payload: Any? = nil) -> Location? {
I would leave it like `public static func parse(url: NSURL, payload: Any? = nil)`. Thought? @onmyway133 @zenangst @RamonGilabert ?

2016-10-05 10:44 UTC, zenangst commented on Sources/Compass.swift
> +  public static func parse(_ url: URL, payload: Any? = nil) -> Location? {
Yeah, remove `_`. I like labels :)

2016-10-05 11:32 UTC, vadymmarkov approved these changes

2016-10-06 07:12 UTC, onmyway133 commented on Compass.podspec
> +  s.pod_target_xcconfig = { 'SWIFT_VERSION' => '3.0' }
thanks

2016-10-06 07:23 UTC, vadymmarkov commented
I've started a GitHub review here and now it's hard to read this PR tbh, it's not clear what is fixed and what is not 😞 But there are 2 comments waiting for your reply @onmyway133 😄

2016-10-06 08:10 UTC, onmyway133 commented on Sources/Compass.swift
> +  static func parseAsURL(_ url: URL, payload: Any? = nil) -> Location? {
I think that `parseAsURL` is actually dealing with url components, so I rename it to `parseComponents`

2016-10-06 08:10 UTC, onmyway133 commented on Sources/Compass.swift
> +  public static func navigate(_ urn: String, scheme: String = Compass.scheme) {
That makes sense

2016-10-06 08:10 UTC, onmyway133 commented on Sources/String+Extensions.swift
> +  func replace(_ string: String, with withString: String) -> String {
Sure

2016-10-10 13:33 UTC, onmyway133 commented on Sources/TypeAlias.swift
> +  public typealias CurrentController = NSViewController
We preserve `Controller` for another use case?

2016-10-10 20:05 UTC, zenangst commented on Sources/TypeAlias.swift
> +  public typealias CurrentController = NSViewController
I had a conflict with `Controller` in `Spots` so I decided to change this one to no "kidnap" the name.

2016-10-10 20:51 UTC, onmyway133 commented on Sources/TypeAlias.swift
> +  public typealias CurrentController = NSViewController
@zenangst oh ja, because we have `struct Compass` so the namespace is lost

2016-10-11 05:28 UTC, zenangst commented on Sources/TypeAlias.swift
> +  public typealias CurrentController = NSViewController
I think we should try and fix that thing, now is probably a good idea to address it as we are already doing some breaking changes in the migration. (breaking as in having to adopt new Swift 3 syntax).

2016-10-13 10:31 UTC, merged